### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [abbreviatedman/dangerroom#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license or a screen shot.

Please add a screen shot so people can see what the theme will look like without having to install it.
Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one.

**Comment by abbreviatedman** [comment]
It took this long for no good reason, but the license and screenshot were added. Thanks so much for the push and for adding it to your list!

**Comment by unixorn** [comment]
Added in 
https://github.com/unixorn/awesome-zsh-plugins/pull/667
